language: node_js

node_js:
  - 6.10.0

after_script:
  # - npm install coveralls
  # - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

env:
  matrix:
    - _BROWSER: "chrome"
      _PLATFORM: "Linux"
    - _BROWSER: "chrome"
      _PLATFORM: "OS_X_10.12"
    - _BROWSER: "chrome"
      _PLATFORM: "Windows_7"
    - _BROWSER: "chrome"
      _PLATFORM: "Windows_10"
    - _BROWSER: "firefox"
      _PLATFORM: "Linux"
    - _BROWSER: "firefox"
      _PLATFORM: "OS_X_10.12"
    - _BROWSER: "firefox"
      _PLATFORM: "Windows_7"
    - _BROWSER: "firefox"
      _PLATFORM: "Windows_10"
    - _BROWSER: "internet_explorer"
      _PLATFORM: "Windows_7"
    - _BROWSER: "internet_explorer"
      _PLATFORM: "Windows_10"
    - _BROWSER: "MicrosoftEdge"
      _PLATFORM: "Windows_10"
    - _BROWSER: "safari"
      _PLATFORM: "OS_X_10.12"
    - _BROWSER: "opera"
      _PLATFORM: "Linux"
    - _BROWSER: "opera"
      _PLATFORM: "Windows_7"
    - _BROWSER: "Safari"
      _PLATFORM: "iOS"
    - _BROWSER: "Browser"
      _PLATFORM: "Android"
