language: node_js

node_js:
  - 4.2.4

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

env:
  matrix:
    - _BROWSER: "chrome"
      _PLATFORM: "Windows_8"
      _VERSION: "48"
    - _BROWSER: "firefox"
      _PLATFORM: "Windows_8"
      _VERSION: "44"
    - _BROWSER: "internet_explorer"
      _PLATFORM: "Windows_8"
      _VERSION: "10"
